return {
  "zaldih/themery.nvim",
  lazy = false,
  config = function()
    require("themery").setup({
      themes = {
        "ayu",
        "base16-atelier-savanna",
        "base16-sandcastle",
        "base2tone_cave_dark",
        "base2tone_desert_dark",
        "base2tone_drawbridge_dark",
        "base2tone_earth_dark",
        "base2tone_field_dark",
        "base2tone_forest_dark",
        "base2tone_garden_dark",
        "base2tone_heath_dark",
        "base2tone_lake_dark",
        "base2tone_lavender_dark",
        "base2tone_mall_dark",
        "base2tone_meadow_dark",
        "base2tone_motel_dark",
        "base2tone_pool_dark",
        "base2tone_porch_dark",
        "base2tone_sea_dark",
        "base2tone_space_dark",
        "base2tone_suburb_dark",
        "base2tone_morning_dark",
        "caret",
        "catppuccin",
        "darkvoid",
        "eldritch",
        "everforest",
        "gruvbox",
        "jellybeans",
        "kanagawa",
        "melange",
        "nightfox",
        "tokyonight",
        "vague",
      },
      livePreview = true,
    })
  end,
}
